# Generated by Django 5.1 on 2024-09-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
    ]
