# Generated by Django 5.1 on 2024-09-15 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('total_value', models.FloatField()),
                ('invested_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=10)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
